public class Album {

    private static String DEFAULT_NAME = "Renaissance";
    private static String DEFAULT_ARTIST = "Beyonce";
    private static String DEFAULT_GENRE = "easy listening";
    private static int DEFAULT_SONG_COUNT = 10;

    private String name;
    private String artist;
    private String genre;
    private int songCount;

    Album() {
        this.name = DEFAULT_NAME;
        this.artist = DEFAULT_ARTIST;
        this.genre = DEFAULT_GENRE;
        this.songCount = DEFAULT_SONG_COUNT;
    }

    Album(String name, String artist, String genre, int songCount) {
        this.setName(name);
        this.setArtist(artist);
        this.setGenre(genre);
        this.setSongCount(songCount);
    }

    // Generated by IntelliJ
    @Override
    public String toString() {
        return "Album{" +
                "name='" + name + '\'' +
                ", artist='" + artist + '\'' +
                ", genre='" + genre + '\'' +
                ", songCount=" + songCount +
                '}';
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        switch (genre) {
            case "easy listening":
            case "hip-hop":
            case "orchestral":
            case "your parents":
            case "theatre":
                this.genre = genre;
                break;
            default:
                this.genre = "easy listening";
                break;
        }
    }

    public int getSongCount() {
        return songCount;
    }

    public void setSongCount(int songCount) {
        this.songCount = (songCount >= 10) ? songCount : 10;
    }

    public boolean isLong() {
        return this.songCount > 50;
    }

}
